/**
 * 内置 MCP 服务器预置定义
 * 常见的 @modelcontextprotocol 官方服务器
 * @author weibin
 */
import type { McpServer } from '../../shared/types'

const NOW = new Date().toISOString()

export const BUILTIN_MCPS: McpServer[] = [
  {
    id: 'mcp-filesystem',
    name: '文件系统',
    description: '允许 AI 读写本地文件系统，适用于文件操作类任务（需要 claude-code 或 iflow）',
    category: 'filesystem',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-filesystem',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    isGlobalEnabled: false,
    tags: ['filesystem', 'files', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-git',
    name: 'Git 操作',
    description: '提供 Git 仓库操作能力，包括查看历史、分支管理、diff 等（需要 Python 环境，通过 uvx 运行）',
    category: 'code',
    transport: 'stdio',
    command: 'uvx',
    args: ['mcp-server-git', '--repository', '.'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    isInstalled: false,
    installMethod: 'pip',
    installCommand: 'pip install mcp-server-git',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    isGlobalEnabled: false,
    tags: ['git', 'vcs', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-sqlite',
    name: 'SQLite 数据库',
    description: '直接查询和操作 SQLite 数据库文件，适合本地数据分析（需要 Python 环境，通过 uvx 运行）',
    category: 'database',
    transport: 'stdio',
    command: 'uvx',
    args: ['mcp-server-sqlite'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        DB_PATH: { type: 'string', description: 'SQLite 数据库文件路径', default: './database.db' },
      },
    },
    isInstalled: false,
    installMethod: 'pip',
    installCommand: 'pip install mcp-server-sqlite',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    isGlobalEnabled: false,
    tags: ['database', 'sqlite', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-github',
    name: 'GitHub API',
    description: '访问 GitHub API，包括 Issues、PR、仓库操作、代码搜索等',
    category: 'code',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        GITHUB_PERSONAL_ACCESS_TOKEN: {
          type: 'string',
          description: 'GitHub Personal Access Token（需要 repo 权限）',
        },
      },
      required: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
    },
    envVars: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-github',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    isGlobalEnabled: false,
    tags: ['github', 'git', 'api', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-brave-search',
    name: 'Brave 搜索',
    description: '使用 Brave Search API 进行网络搜索，获取实时网络信息',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        BRAVE_API_KEY: { type: 'string', description: 'Brave Search API Key（从 brave.com/search/api 获取）' },
      },
      required: ['BRAVE_API_KEY'],
    },
    envVars: { BRAVE_API_KEY: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-brave-search',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    isGlobalEnabled: false,
    tags: ['search', 'web', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mcp-postgres',
    name: 'PostgreSQL',
    description: '连接和查询 PostgreSQL 数据库，支持 SQL 查询和 schema 探索',
    category: 'database',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    compatibleProviders: ['claude-code', 'iflow'],
    fallbackMode: 'disabled',
    configSchema: {
      type: 'object',
      properties: {
        POSTGRES_CONNECTION_STRING: {
          type: 'string',
          description: 'PostgreSQL 连接字符串，格式：postgresql://user:password@localhost:5432/dbname',
        },
      },
      required: ['POSTGRES_CONNECTION_STRING'],
    },
    envVars: { POSTGRES_CONNECTION_STRING: '' },
    isInstalled: false,
    installMethod: 'npm',
    installCommand: 'npm install -g @modelcontextprotocol/server-postgres',
    source: 'builtin',
    version: 'latest',
    author: 'Anthropic',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    isGlobalEnabled: false,
    tags: ['database', 'postgresql', 'official'],
    createdAt: NOW,
    updatedAt: NOW,
  },
]
